[tool.black]
line-length = 99
skip-numeric-underscore-normalization = 1
exclude = '(migrations/)'

[tool.isort]
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
line_length = 99
skip_glob="**/migrations/**"
src_paths = ""
